In [6]:
import os
import torch
import numpy as np

In [2]:
cd ../MNC

[Errno 2] No such file or directory: '../MNC'
/home/kahlua/fgnn/images


In [4]:
cd ../../MNC

/home/kahlua/MNC


In [5]:
mv *.pt ../fgnn


In [6]:
cd ../fgnn

/home/kahlua/fgnn


In [7]:
mv vaild.pt err.pt ldpc_data

mv: cannot stat 'vaild.pt': No such file or directory


In [8]:
ls *.pt

ldpc_virtual.pt  ldpc_virtual_t.pt  valid.pt


In [9]:
mv valid.pt ldpc_data

In [10]:
cd ldpc_data

/home/kahlua/fgnn/ldpc_data


In [12]:
cd ..

/home/kahlua/fgnn


In [13]:
ls model_ldpc/

train_syn_hop_factor_mp_nn_factor_at_2020-05-02_04:35:41/


In [20]:
ls model_ldpc/

train_syn_hop_factor_mp_nn_factor_at_2020-05-02_04:35:41/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:01:56/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:03:43/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:07:38/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:11:00/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:13:06/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:15:39/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:35:37/
train_syn_hop_factor_mp_nn_factor_at_2020-05-02_07:41:39/


In [21]:
pwd

'/home/kahlua/fgnn'

In [22]:
cd logs

/home/kahlua/fgnn/logs


In [24]:
files = os.listdir('.')

In [27]:
for file in files:
    size = os.path.getsize(file)
    print(size)

6601
6691
7369
6714
0
11403
6593
12022
6704
6691
6790
6691
11403
0
6691
11561
8034
6691
6695
6790
228380
11394
70556
6691
6729
7482
6691
6578
6869
6699
6691
8045
6691
11394
6691
26065
6704
6786
11403
6601
6784
11392
6790
6580
6707
6704
6601


In [2]:
cd ~/MNC

/home/kahlua/MNC


In [3]:
ls *.pt

err.pt  valid.pt


In [7]:
data = torch.load('valid.pt')

In [8]:
data.keys()

dict_keys(['node_feature', 'hop_feature', 'y', 'sigma_b'])

In [9]:
data['sigma_b']

tensor([4, 3, 4, 5, 2, 4, 4, 3, 0, 2, 3, 4, 0, 4, 3, 2, 2, 0, 5, 4, 0, 5, 3, 5,
        3, 0, 4, 5, 4, 3, 1, 4, 5, 5, 2, 5, 5, 2, 3, 1, 0, 0, 0, 0, 5, 2, 3, 3,
        4, 0, 3, 0, 1, 4, 5, 3, 1, 1, 3, 1, 5, 3, 1, 1, 2, 4, 2, 1, 2, 3, 0, 4,
        0, 1, 3, 0, 5, 4, 0, 2, 0, 2, 5, 4, 5, 3, 1, 3, 1, 3, 3, 0, 3, 3, 2, 0,
        5, 4, 4, 0, 4, 5, 0, 1, 2, 1, 2, 2, 0, 5, 5, 5, 0, 2, 0, 5, 2, 2, 1, 3,
        0, 4, 3, 0, 3, 5, 0, 0, 5, 3, 2, 4, 2, 5, 3, 2, 5, 4, 5, 0, 4, 0, 2, 2,
        1, 2, 2, 1, 4, 4, 0, 5, 2, 2, 5, 3, 0, 5, 3, 2, 2, 0, 3, 5, 3, 0, 2, 1,
        0, 4, 0, 4, 4, 2, 4, 5, 2, 0, 5, 0, 0, 2, 2, 0, 2, 0, 2, 4, 5, 0, 0, 3,
        1, 4, 2, 1, 5, 0, 2, 0, 0, 2, 1, 3, 3, 0, 1, 0, 1, 3, 5, 2, 0, 2, 3, 1,
        4, 4, 4, 5, 5, 2, 0, 4, 4, 1, 2, 0, 2, 3, 1, 5, 0, 3, 5, 0, 3, 1, 5, 5,
        4, 3, 2, 4, 3, 2, 3, 5, 4, 3, 4, 4, 0, 1, 3, 0, 2, 5, 1, 1, 4, 1, 2, 4,
        2, 2, 4, 4, 3, 1, 0, 5, 4, 0, 1, 5, 5, 1, 3, 2, 3, 4, 0, 1, 3, 1, 1, 4,
        4, 5, 4, 4, 2, 2, 1, 3, 3, 2, 2,

In [26]:
node_feature = data['node_feature']

In [30]:
cur_SNR = node_feature[:,1,0,0]

In [31]:
sigma_b = data['sigma_b']

In [34]:
indice = (sigma_b == 0)

In [36]:
indice2 = (abs(cur_SNR-1.2589)<1e-3)

In [41]:
indice & indice2

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False,  True, False,
        False, False,  True, False,  True, False, False, False, False, False,
         True, False, False,  True, False, False,  True,  True, 

In [42]:
torch.sum(indice)

tensor(98)

In [45]:
x = np.random.randn(2,2)
y = np.random.randn(2,2)


In [51]:
np.divide(x,y)

array([[ 0.91983965,  0.76578617],
       [-5.13293056, -1.24277386]])

In [47]:
x

array([[-0.9072665 ,  0.90879019],
       [-2.67607036, -1.52350057]])

In [48]:
y

array([[-0.98633115,  1.18674145],
       [ 0.52135331,  1.2258872 ]])

In [3]:
cd ../ldpc_data

/home/kahlua/fgnn/ldpc_data


In [7]:
err_97 = torch.load('err_97.pt')

In [23]:
(err_97['err_mean'] / 48)

array([[0.10729167, 0.15277778, 0.11538462, 0.12390351, 0.13932292,
        0.14166667],
       [0.01602564, 0.01111111, 0.03958333, 0.04017857, 0.03685897,
        0.05729167],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [18]:
ls

err_2.pt   err_97.pt  train_42.pt  valid_2.pt   valid_97.pt
err_77.pt  err.pt     train.pt     valid_77.pt  valid.pt


In [19]:
data = torch.load('train_42.pt')

In [20]:
data['hop_feature'].shape

torch.Size([50000, 9, 48, 1])